lib: [
  "_build/install/default/lib/socks_client/META" {"META"}
  "_build/install/default/lib/socks_client/opam" {"opam"}
  "_build/install/default/lib/socks_client/socks_client.a" {"socks_client.a"}
  "_build/install/default/lib/socks_client/socks_client.cma" {"socks_client.cma"}
  "_build/install/default/lib/socks_client/socks_client.cmi" {"socks_client.cmi"}
  "_build/install/default/lib/socks_client/socks_client.cmt" {"socks_client.cmt"}
  "_build/install/default/lib/socks_client/socks_client.cmti" {"socks_client.cmti"}
  "_build/install/default/lib/socks_client/socks_client.cmx" {"socks_client.cmx"}
  "_build/install/default/lib/socks_client/socks_client.cmxa" {"socks_client.cmxa"}
  "_build/install/default/lib/socks_client/socks_client.cmxs" {"socks_client.cmxs"}
  "_build/install/default/lib/socks_client/socks_client.dune" {"socks_client.dune"}
  "_build/install/default/lib/socks_client/socks_client.ml" {"socks_client.ml"}
  "_build/install/default/lib/socks_client/socks_client.mli" {"socks_client.mli"}
]
doc: [
  "_build/install/default/doc/socks_client/CHANGES.md"
  "_build/install/default/doc/socks_client/LICENSE.md"
  "_build/install/default/doc/socks_client/README.md"
]
